<a href="https://colab.research.google.com/github/SudarshanPoudel/deep-learning-reboot/blob/main/01_pytorch_revision/01_tensers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setting up

In [1]:
import torch

torch.__version__

'2.6.0+cu124'

In [2]:
torch.cuda.is_available()

True

# creating a tensor

In [3]:
a = torch.empty(2, 3)
a

tensor([[7.8970e-25, 4.5426e-41, 0.0000e+00],
        [0.0000e+00, 1.9618e-44, 9.2196e-41]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.rand(6, 2)

tensor([[0.6378, 0.0952],
        [0.9583, 0.9363],
        [0.0078, 0.1118],
        [0.2558, 0.0295],
        [0.8945, 0.2157],
        [0.5767, 0.4511]])

In [7]:
torch.manual_seed(42)
torch.rand(6, 2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

In [8]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [9]:
torch.eye(7)

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

# Tensor shapes

In [10]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [11]:
torch.empty_like(x)

tensor([[                  0,                   0, 2314885530279477261],
        [          996319104, 7881701906593088616,           996319136]])

# Tensor data types

In [12]:
x.dtype

torch.int64

In [13]:
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float16)
y.dtype

torch.float16

In [14]:
x.to(torch.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [15]:
x.dtype

torch.int64

# Mathematical Operations

In [16]:
x = torch.tensor([[1, 2], [3, 4]])
x/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [17]:
y = torch.tensor([[5, 6], [7, -8]])
x + y

tensor([[ 6,  8],
        [10, -4]])

In [18]:
torch.absolute(y)

tensor([[5, 6],
        [7, 8]])

In [19]:
torch.clamp(x, min=2, max=3)

tensor([[2, 2],
        [3, 3]])

In [20]:
torch.sum(x)

tensor(10)

In [21]:
torch.sum(x, dim=0)

tensor([4, 6])

# Matrix Operations

In [22]:
x = torch.tensor([[1, 2], [2,3], [3, 4]], dtype=torch.float16)
y = torch.tensor([[5, 6], [6, 7]], dtype=torch.float16)
torch.matmul(x, y)

tensor([[17., 20.],
        [28., 33.],
        [39., 46.]], dtype=torch.float16)

In [23]:
torch.transpose(x, 0, 1)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float16)

In [26]:
z = torch.tensor([[1, 11], [10, 2]], dtype=torch.float16)
y > z

tensor([[ True, False],
        [False,  True]])

# Special function

In [7]:
a = torch.randint(size=(2, 3), high=9, low=-10, dtype=torch.float32)
a

tensor([[-4.,  3.,  3.],
        [-1.,  6.,  3.]])

In [29]:
torch.log(a)

tensor([[1.0986, 1.0986, 2.0794],
        [1.6094, 1.3863, 2.0794]])

In [30]:
torch.exp(a)

tensor([[  20.0855,   20.0855, 2980.9580],
        [ 148.4132,   54.5981, 2980.9580]])

In [31]:
torch.sqrt(a)

tensor([[1.7321, 1.7321, 2.8284],
        [2.2361, 2.0000, 2.8284]])

In [32]:
torch.sigmoid(a)

tensor([[0.9526, 0.9526, 0.9997],
        [0.9933, 0.9820, 0.9997]])

In [33]:
torch.softmax(a, dim=1)

tensor([[0.0066, 0.0066, 0.9867],
        [0.0466, 0.0171, 0.9362]])

In [38]:
torch.relu(a)

tensor([[4., 0., 0.],
        [0., 0., 0.]])

# Inplace operators

In [43]:
a.add_(x.transpose(0, 1))

tensor([[ 5.,  0.,  3.],
        [ 1., -1.,  0.]])

In [44]:
a

tensor([[ 5.,  0.,  3.],
        [ 1., -1.,  0.]])

In [45]:
b = a
a[0][0] = 0
b

tensor([[ 0.,  0.,  3.],
        [ 1., -1.,  0.]])

In [46]:
id(a)

139226162543888

In [47]:
id(b)

139226162543888

In [48]:
b = a.clone()
a[0][0] = 1
b

tensor([[ 0.,  0.,  3.],
        [ 1., -1.,  0.]])

In [49]:
id(a)

139226162543888

In [50]:
id(b)

139225730976848

# Tensor in GPU

In [3]:
import torch
import time

if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(f"device: {device}")

device: cuda


In [4]:
torch.rand((2, 3), device=device)

tensor([[0.6965, 0.6781, 0.9205],
        [0.9130, 0.7475, 0.7770]], device='cuda:0')

In [8]:
a.device

device(type='cpu')

In [9]:
b = a.to(device)

In [10]:
b

tensor([[-4.,  3.,  3.],
        [-1.,  6.,  3.]], device='cuda:0')

In [15]:
size = 10000

cpu_mat1 = torch.randn(size, size)
cpu_mat2 = torch.randn(size, size)

start = time.time()
result_cpt = torch.matmul(cpu_mat1, cpu_mat2)
print(f"CPU time: {time.time() - start}")

CPU time: 17.286661863327026


In [16]:
gpu_mat1 = torch.randn(size, size, device=device)
gpu_mat2 = torch.randn(size, size, device=device)

start = time.time()
result_cpt = torch.matmul(gpu_mat1, gpu_mat2)
print(f"GPU time: {time.time() - start}")

GPU time: 0.13168072700500488
